rootcolor={{colors.background.dark.hex_stripped}}ff

bordercolor={{colors.outline_variant.dark.hex_stripped}}ee

focuscolor={{colors.primary_container.dark.hex_stripped}}80

maxmizescreencolor={{colors.secondary.dark.hex_stripped}}80

urgentcolor={{colors.error.dark.hex_stripped}}ff

scratchpadcolor={{colors.tertiary.dark.hex_stripped}}80

globalcolor={{colors.secondary_container.dark.hex_stripped}}80

overlaycolor={{colors.tertiary_container.dark.hex_stripped}}80
