# layer rules
layerrule=animation_type_open:zoom,layer_name:wofi
layerrule=animation_type_close:zoom,layer_name:wofi
layerrule=noblur:1,layer_name:selection

# window rules


# monitor rules set your monitor rules if you want them to work
monitorrule=eDP-1,0.55,1,tile,0,1,0,0,1920,1080,144
