[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = "pgrep btop> /dev/null 2>&1 && pkill -12 btop || echo 'no btop'"

[templates.dunst]
input_path = './templates/dunstrc-colors'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/matugen-theme.conf'
post_hook = 'kitty +kitten themes --reload-in=all Matugen-Theme'

[templates.fish]
input_path = './templates/colors.fish'
output_path = '~/.config/fish/themes/matugen.fish'
post_hook = 'fish -C "source ~/.config/fish/themes/matugen.fish"'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/your-theme'
post_hook = "pgrep cava > /dev/null 2>&1 && pkill -10 cava || echo 'no cava'"

[templates.mango]
input_path = './templates/mango-colors.conf'
output_path = '~/.config/mango/matugen-colors.conf'
post_hook = 'mmsg -d reload_config'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.wlogout]
input_path = './templates/colors.css'
output_path = '~/.config/wlogout/colors.css'
