#!/bin/sh
#	systats script, largely based on bread on penguins implementation at https://github.com/BreadOnPenguins/scripts/blob/master/statusbar/systemstats

#	Cpu temp retrieval using the sensors command and awk language. read the GNU guide or AWK book for more info
#	sensors (pipe using '|') | awk /regex(at the beggining of a strig using '^' and checking for multiple regex's with or '|')
#	


CPU_TEMP=$(sensors | mawk -W posix '/^Package id|^Core 0|^temp1/ { 
		gsub(/[+°C]/, "");
				for (i=1; i<=NF; i++) 
						{
								if ($i ~ /^[0-9]+(\.[0-9]+)?$/) {
										gsub(/\..*/, "", $i);
												print $i;
												exit;
										}
						}
		}')

# Array of disks and matching icons
DISK1=$(df -h "/")
DISK2=$(lsblk)

MEM=$(free -m | mawk  -W posix '/^M/{ram=$3*100/$2; 
										printf "%.1f",ram}')
CPU_USE=$(iostat | mawk -W posix '/avg-cpu/ {getline;print "User CPU: "$1"% \n\nSystem CPU: "$3"%"}')

case $CPU_TEMP in
    "N/A") COLOR="$background" && CPU_ICON="?" ;;
    [7-9][6-9]|[8-9][0-9]|100) COLOR="#bf616a" && CPU_ICON="" ;;  # Greater than 75
    [6][6-9]|7[0-5]) COLOR="#ebcb8b" && CPU_ICON="" ;;            # Between 66 and 75
    *) COLOR="#a3be8c" && CPU_ICON="" ;;                          # 65 or below
esac
#	send the temp value to the bar
echo "[$MEM% $CPU_ICON$CPU_TEMP°C]"

case $BLOCK_BUTTON in
		1) setsid -wf kitty -e btop ;;
		2) setsid -wf kitty -e vi "$0" ;;
		3) notify-send -t 10000 -h string:bgcolor:$COLOR Stats "$CPU_USE\n" ;;
esac
