#!/bin/bash

#variables
notification_timeout=1000
step=2

# Get brightness
get_brightness() {
	brightnessctl -m | cut -d, -f4 | sed 's/\%//'
}

# Get icons
get_icon() {
	current=$(get_brightness)
	if [ "$current" -le "10" ] ; then
		icon="󱩎"
	elif [ "$current" -le "20" ] ; then
		icon="󱩏"
	elif [ "$current" -le "30" ] ; then
		icon="󱩐"
	elif [ "$current" -le "40" ] ; then
		icon="󱩑"
	elif [ "$current" -le "50" ] ; then
		icon="󱩒"
	elif [ "$current" -le "60" ] ; then
		icon="󱩓"
	elif [ "$current" -le "70" ] ; then
		icon="󱩔"
	elif [ "$current" -le "80" ] ; then
		icon="󱩕"
	elif [ "$current" -le "90" ] ; then
		icon="󱩖"
	else
		icon="󰛨"
	fi
}

# Send Notification/OSD
notify_user() {
	notify-send -e -h string:x-canonical-private-synchronous:osd -h int:value:$current -u low  "$icon $current%"
}

# change brightness
change_brightness() {
	local current_brightness
	current_brightness=$(get_brightness)

	# calculate new brightness
	if [[ "$1" == "+${step}%" ]]; then
		new_brightness=$((current_brightness + step))
	elif [[ "$1" == "-${step}%" ]]; then
		new_brightness=$((current_brightness - step))
	fi

	if (( new_brightness < 5 )); then
		new_brightness=5
	elif (( new_brightness > 100 )); then
		new_brightness=100
	fi

	brightnessctl set "${new_brightness}%"
	get_icon
	current=$new_brightness
	notify_user
}

# Execute accordingly

case "$1" in
	"--get")
		get_brightness
		;;
	"--inc")
		change_brightness "+${step}%"
		;;
	"--dec")
		change_brightness "-${step}%"
		;;
	*)
		get_brightness
		;;
esac

