#!/bin/sh

#[ -f ~/.cache/wal/colors.sh ] && . ~/.cache/wal/colors.sh

#CHOICE=$(echo | dmenu -c -nb $background -nf $color4 -sb $color4 -sf $color0 -l 3 -i -p "Escoge una opción:" )

case "$XDG_SESSION_TYPE" in
		x11)
				maim -f "png" -m 10 -Bs -b 5.0 -c 255.0,255.0,255.0,0.65 -l | swappy -f -
				;;
		wayland)
				grim -g "$(slurp)" - | swappy -f -
				;;
esac
