set fish_color_autosuggestion {{colors.secondary_fixed_dim.default.hex_stripped}}
set fish_color_cancel {{colors.on_error.default.hex_stripped}} 
set fish_color_command {{colors.primary.default.hex_stripped}}
set fish_color_comment {{colors.outline.default.hex_stripped}}
set fish_color_cwd {{colors.secondary.default.hex_stripped}}
set fish_color_cwd_root {{colors.secondary.default.hex_stripped}}
set fish_color_end {{colors.secondary_fixed.default.hex_stripped}}
set fish_color_error {{colors.error.default.hex_stripped}}
set fish_color_escape {{colors.primary_fixed.default.hex_stripped}}
set fish_color_history_current --bold
set fish_color_host {{colors.primary_container.default.hex_stripped}}
set fish_color_host_remote {{colors.primary_container.default.hex_stripped}}
set fish_color_keyword {{colors.tertiary.default.hex_stripped}}
set fish_color_match --background={{colors.primary_fixed.default.hex_stripped}}
set fish_color_normal {{colors.secondary.default.hex_stripped}}
set fish_color_operator {{colors.secondary_fixed_dim.default.hex_stripped}}
set fish_color_option {{colors.on_secondary_container.default.hex_stripped}}
set fish_color_param {{colors.secondary_fixed_dim.default.hex_stripped}}
set fish_color_quote {{colors.tertiary_fixed.default.hex_stripped}}
set fish_color_redirection {{colors.on_surface_variant.default.hex_stripped}}
set fish_color_search_match --background={{colors.tertiary_fixed_dim.default.hex_stripped}}
set fish_color_selection --background={{colors.surface_tint.default.hex_stripped}}
set fish_color_status {{colors.inverse_primary.default.hex_stripped}}
set fish_color_user {{colors.primary.default.hex_stripped}}
set fish_color_valid_path --underline

set fish_pager_color_background {{colors.background.default.hex_stripped}}
set fish_pager_color_completion {{colors.secondary.default.hex_stripped}}
set fish_pager_color_description {{colors.inverse_surface.default.hex_stripped}}
set fish_pager_color_prefix {{colors.on_tertiary.default.hex_stripped}}
set fish_pager_color_progress {{colors.surface_container_highest.default.hex_stripped}}
set fish_pager_color_secondary_background {{colors.surface_container.default.hex_stripped}}
set fish_pager_color_secondary_completion {{colors.on_primary_fixed_variant.default.hex_stripped}}
set fish_pager_color_secondary_description {{colors.on_surface.default.hex_stripped}}
set fish_pager_color_secondary_prefix {{colors.on_secondary_container.default.hex_stripped}}
set fish_pager_color_selected_background --background={{colors.surface_variant.default.hex_stripped}}
set fish_pager_color_selected_completion {{colors.tertiary_fixed_dim.default.hex_stripped}}
set fish_pager_color_selected_description {{colors.on_tertiary_container.default.hex_stripped}}
set fish_pager_color_selected_prefix {{colors.tertiary_fixed_dim.default.hex_stripped}}
